semi: false
singleQuote: true
importOrder: ["^(react/(.*)$)|^(react$)", "^@remix-run/(.*)$", "<THIRD_PARTY_MODULES>", "^[.~/]"]
importOrderSeparation: true
importOrderSortSpecifiers: true
plugins: ["@trivago/prettier-plugin-sort-imports"]
