// Cloudflare Pages functions are not minified by default.
// So I bundle /functions/[[path]].js with esbuild to minify it.
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages'

// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from 'build/server'

export const onRequest = createPagesFunctionHandler({
  // @ts-expect-error - this error only occurs with exactOptionalPropertyTypes enabled.
  build,
})
