// Generated by Wrangler on Tue Mar 05 2024 11:41:40 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	SESSION_KV: KVNamespace;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	CALLBACK_URL: string;
	SESSION_SECRET: string;
	BUCKET: R2Bucket;
	DB: D1Database;
}
