name = "blog"
main = "./dist/index.js"
compatibility_date = "2025-08-08"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "77f4589e-54f5-43ad-ab44-ccc96e048bfc"
preview_database_id = "fe62b702-8f6b-4b85-81c0-e315529e6ca7"

[[kv_namespaces]]
binding = "KV"
id = "d5a0fdf0da6541dabb9caac6bbc6b898"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "blog-images"
