[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "blog-db"
database_id = "77f4589e-54f5-43ad-ab44-ccc96e048bfc"

[[d1_databases]]
binding = "DB_PREVIEW"
database_name = "blog-db-preview"
database_id = "fe62b702-8f6b-4b85-81c0-e315529e6ca7"

kv_namespaces = [
  { binding = "SESSION_KV", id = "4fee0af77fa3425dac9bd8dc5bfbaf4b", preview_id = "4fee0af77fa3425dac9bd8dc5bfbaf4b" }
]
